bet_types = {
        'winner': {
            'id': 11,
            'name': 'Winner',
            'short-name': 'Winner',
            'position': '0',
        },
        '1x2': {
            'id': 1,
            'name': '1X2',
            'short-name': '1X2',
            'position': '1',
        },
        'home-away': {
            'id': 3,
            'name': 'Home/Away',
            'short-name': 'Home/Away',
            'position': '2',
        },
        'ah': {
            'id': 5,
            'name': 'Asian Handicap',
            'short-name': 'AH',
            'position': '3',
        },
        'over-under': {
            'id': 2,
            'name': 'Over/Under',
            'short-name': 'O/U',
            'position': '4',
        },
        'dnb': {
            'id': 6,
            'name': 'Draw No Bet',
            'short-name': 'DNB',
            'position': '5',
        },
        'eh': {
            'id': 12,
            'name': 'European Handicap',
            'short-name': 'EH',
            'position': '6',
        },
        'dc': {
            'id': 4,
            'name': 'Double Chance',
            'short-name': 'DC',
            'position': '7',
        },
        'tq': {
            'id': 7,
            'name': 'To Qualify',
            'short-name': 'TQ',
            'position': '8',
        },
        'cs': {
            'id': 8,
            'name': 'Correct Score',
            'short-name': 'CS',
            'position': '9',
        },
        'ht-ft': {
            'id': 9,
            'name': 'Half Time / Full Time',
            'short-name': 'HT/FT',
            'position': '10',
        },
        'o-e': {
            'id': 10,
            'name': 'Odd or Even',
            'short-name': 'O/E',
            'position': '11',
        },
        'bts': {
            'id': 13,
            'name': 'Both Teams to Score',
            'short-name': 'BTS',
            'position': '12',
        }
    }

bet_scope = {
        '1': 'FT including OT',
        '2': 'Full Time',
        '3': '1st Half',
        '4': '2nd Half',
        '5': '1st Period',
        '6': '2nd Period',
        '7': '3rd Period',
        '8': '1Q',
        '9': '2Q',
        '10': '3Q',
        '11': '4Q',
        '12': '1st Set',
        '13': '2nd Set',
        '14': '3rd Set',
        '15': '4th Set',
        '16': '5th Set',
        '17': '1st Inning',
        '18': '2nd Inning',
        '19': '3rd Inning',
        '20': '4th Inning',
        '21': '5th Inning',
        '22': '6th Inning',
        '23': '7th Inning',
        '24': '8th Inning',
        '25': '9th Inning',
        '26': 'Next Set',
        '27': 'Current Set',
        '28': 'Next Game',
        '29': 'Current Game'
    }

sport = {
        "soccer": 1,
        "basketball": 3,
        "baseball": 6,
        "hockey": 4,
        "tennis": 2,
        "american-football": 5,
        "aussie-rules": 18,
        "badminton": 21,
        "bandy": 10,
        "beach-soccer": 26,
        "beach-volleyball": 17,
        "boxing": 16,
        "cricket": 13,
        "darts": 14,
        "esports": 36,
        "floorball": 9,
        "futsal": 11,
        "handball": 7,
        "mma": 28,
        "pesapallo": 30,
        "rugby-league": 19,
        "rugby-union": 8,
        "snooker": 15,
        "volleyball": 12,
        "water-polo": 22
    }
